apiVersion: v1
kind: Secret
metadata:
  name: konnectivity-server
data:
  server.crt: {{ pki "konnectivity-server.crt" }}
  server.key: {{ pki "konnectivity-server.key" }}
  local-server.crt: {{ pki "konnectivity-server-local.crt" }}
  local-server.key: {{ pki "konnectivity-server-local.key" }}
