apiVersion: v1
kind: Service
metadata:
  name: konnectivity-server-local
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: konnectivity-server
  type: ClusterIP
